# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('fathers_name', models.CharField(max_length=250)),
                ('mothers_name', models.CharField(max_length=250)),
                ('contact_number', models.IntegerField()),
                ('dob', models.DateTimeField()),
            ],
        ),
    ]
