# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTWF', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='dob',
            field=models.DateField(),
        ),
    ]
