# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTWF', '0002_auto_20170907_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='contact_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='dob',
            field=models.DateField(blank=True),
        ),
    ]
