# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTWF', '0003_auto_20170907_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='info',
            name='course',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=2),
        ),
        migrations.AddField(
            model_name='info',
            name='occupation',
            field=models.CharField(default='Ishan', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
