# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTWF', '0004_auto_20170907_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='mothers_name',
        ),
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='course',
            field=models.CharField(choices=[('c', 'C'), ('c++', 'C++'), ('c#', 'C#'), ('python', 'PYTHON'), ('java', 'JAVA')], default='c', max_length=2),
        ),
    ]
