# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTWF', '0005_auto_20170907_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='info',
            name='occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
