# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTWF', '0006_auto_20170907_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='course',
            field=models.CharField(choices=[('c', 'C'), ('C++', 'C++'), ('C#', 'C#'), ('PYTHON', 'PYTHON'), ('JAVA', 'JAVA')], default='c', max_length=20),
        ),
    ]
